services:
  websocket:
    build:
      context: ./websocket
      dockerfile: Dockerfile
    image: wongyh01/websocket:1.0
    container_name: websocket
    ports:
      - "5014:5014"
    networks:
      - esd-net
  product_listing:
    build:
      context: ./services/atomic/product_listing
      dockerfile: Dockerfile
    image: wongyh01/product_listing:1.0
    container_name: product_listing
    depends_on:
      - websocket
    env_file:
      - .env
    environment:
      - WEBSOCKET_URL=http://websocket:5014
    ports:
      - "5005:5005"
    networks:
      - esd-net
  product_validation:
    build:
      context: ./services/atomic/product_validation
      dockerfile: Dockerfile
    image: wongyh01/product_validation:1.0
    container_name: product_validation
    env_file:
      - .env
    ports:
      - "5004:5004"
    networks:
      - esd-net
  locating:
    build:
      context: ./services/atomic/locating
      dockerfile: Dockerfile
    image: wongyh01/locating:1.0
    container_name: locating
    env_file:
      - .env
    environment:
      - GRPC_PORT=5006
    ports:
      - "5006:5006"
    networks:
      - esd-net



networks:
  esd-net: