version: "3.8"

services:
  websocket:
    build:
      context: ./websocket
      dockerfile: Dockerfile
    container_name: websocket
    ports:
      - "5014:5014"
    networks:
      - esd-net
  product_listing:
    build:
      context: ./services/atomic/product_listing
      dockerfile: Dockerfile
    container_name: product_listing
    depends_on:
      - websocket
    env_file:
      - .env
    environment:
      - WEBSOCKET_URL=http://websocket:5014
    ports:
      - "5005:5005"
    networks:
      - esd-net



networks:
  esd-net: