version: '3.8'

networks:
  esd-net:
    driver: bridge

services:
  # # PostgreSQL Service
  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_USER: postgres         
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres           
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   networks:
  #     - esd-net
  #   ports:
  #     - "5432:5432"

  # RabbitMQ Service
  rabbitmq:
    image: "rabbitmq:3-management"
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - esd-net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  # AMQP Setup Service
  amqp-setup:
    build:
      context: .
      dockerfile: rabbitmq/Dockerfile
    container_name: amqp-setup
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - esd-net
    restart: "no"

  # publisher:
  #   build:
  #     context: ./services/atomic/testPublisher
  #     dockerfile: Dockerfile
  #   container_name: publisher
  #   depends_on:
  #     - amqp-setup
  #   networks:
  #     - esd-net

  # subscriber:
  #   build:
  #     context: ./services/atomic/testSubscriber
  #     dockerfile: Dockerfile
  #   container_name: subscriber
  #   depends_on:
  #     - amqp-setup
  #   networks:
  #     - esd-net

  hub:
    build:
      context: ./services/atomic/hub
      dockerfile: Dockerfile
    container_name: hub
    ports:
    - 5010:5000
    networks:
    - esd-net
    
  confirm-delivery:
    build:
      context: ./services/composite/confirmDelivery
      dockerfile: Dockerfile
    container_name: confirm-delivery
    ports:
      - 5009:5000
    environment:
      - HUB_SERVICE_URL=http://hub:5000
      - ACCOUNT_SERVICE_URL=https://personal-tdqpornm.outsystemscloud.com/FoodBridge/rest/AccountInfoAPI
    networks:
      - esd-net

volumes:
  rabbitmq_data:
    external: false
