version: '3'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres         
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres           
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - esd-net
    ports:
      - "5432:5432"

  # RabbitMQ Service
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - esd-net

  # AMQP Setup Service
  amqp-setup:
    build: ./services/amqp-setup  # Path to the directory where amqp_setup.py is located
    depends_on:
      - rabbitmq  # Ensure RabbitMQ is up before running this service
    networks:
      - esd-net  # Connect it to the same network as RabbitMQ
    restart: "no"  # Run once and then stop the container

networks:
  esd-net:
    driver: bridge

volumes:
  postgres-data:
    external: false
  rabbitmq_data:
    external: false
