# THIS IS NOT UPDATED YET, COPIED FROM LABS

volumes:
  rabbitmq_data:
    name: esd_rabbitmq_data
    # volumes are persistent data stores for containers
    # created and managed by Docker

networks:
  esd-net:
    driver: bridge
    name: esd-net
    # esd-net is the name of the bridge network, this 
    # allows containers within the same network
    # to communicate with each other

services:

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    # Docker official RabbitMQ image with a tag 3-management
    hostname: esd-rabbit
    # RabbitMQ stores data based on what it calls the "Node Name", 
    # which defaults to the hostname.
    # The container’s hostname defaults to the container’s ID if not specified.
    # We specify a hostname explicitly to keep track of our data. 
    restart: always
    # always restart contaienr if it stops, except when done manually
    ports:
      - "5672:5672"
      - "15672:15672"
      # The port 5672 is used for the RabbitMQ client connections.
      # The port 15672 is for the RabbitMQ management website. 
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
      # Bind the volume ‘rabbitmq_data’ we have defined above 
      # in the top level “volumes” section to the container’s path ‘/var/lib/rabbitmq’. 
      # This is to persist RabbitMQ’s data across container recreation events
    networks:
      - esd-net
      # This attaches the container to the network we have defined above in the top level “networks” section. 